
  CREATE TABLE "USER1"."RESERVATION" 
   (	"CAR" NUMBER, 
	"PEOPLE" NUMBER, 
	"STATE" NUMBER(2,0), 
	 CONSTRAINT "RESERVATIONFK1" FOREIGN KEY ("PEOPLE")
	  REFERENCES "USER1"."PEOPLE" ("ID") ENABLE, 
	 CONSTRAINT "RESERVATIONFK2" FOREIGN KEY ("CAR")
	  REFERENCES "USER1"."CAR" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  
  CREATE TABLE "USER1"."PEOPLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"SURNAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PEOPLEPK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "USER1"."BI_PEOPLE" BEFORE INSERT ON USER1.PEOPLE
	FOR EACH ROW
BEGIN
  SELECT USER1.PEOPLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "USER1"."BI_PEOPLE" ENABLE;
  
  
  
  CREATE TABLE "USER1"."CAR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BRAND" VARCHAR2(50 BYTE), 
	"MODEL" VARCHAR2(50 BYTE), 
	"TYPE" NUMBER(2,0), 
	"PLATE" VARCHAR2(50 BYTE), 
	"SEATS" NUMBER(2,0), 
	 CONSTRAINT "CARPK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "USER1"."BI_CAR" BEFORE INSERT ON USER1.CAR
	FOR EACH ROW
BEGIN
  SELECT USER1.CAR_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "USER1"."BI_CAR" ENABLE;
  