package it.rcpvision.emf.architecture.example.repository.mybatis.mapper;

import it.rcpvision.emf.architecture.example.repository.mybatis.model.People;
import it.rcpvision.emf.architecture.example.repository.mybatis.model.PeopleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PeopleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@SelectProvider(type = PeopleSqlProvider.class, method = "countByExample")
	long countByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@DeleteProvider(type = PeopleSqlProvider.class, method = "deleteByExample")
	int deleteByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@Delete({ "delete from USER1.PEOPLE", "where ID = #{id,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@Insert({ "insert into USER1.PEOPLE (ID, NAME, ", "SURNAME)",
			"values (#{id,jdbcType=DECIMAL}, #{name,jdbcType=VARCHAR}, ", "#{surname,jdbcType=VARCHAR})" })
	int insert(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@InsertProvider(type = PeopleSqlProvider.class, method = "insertSelective")
	int insertSelective(People record);
	
	@Select({"SELECT USER1.PEOPLE_SEQ.currval FROM DUAL"})
	Long getLastId();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@SelectProvider(type = PeopleSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SURNAME", property = "surname", jdbcType = JdbcType.VARCHAR) })
	List<People> selectByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@Select({ "select", "ID, NAME, SURNAME", "from USER1.PEOPLE", "where ID = #{id,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "NAME", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "SURNAME", property = "surname", jdbcType = JdbcType.VARCHAR) })
	People selectByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@UpdateProvider(type = PeopleSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") People record, @Param("example") PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@UpdateProvider(type = PeopleSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") People record, @Param("example") PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@UpdateProvider(type = PeopleSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	@Update({ "update USER1.PEOPLE", "set NAME = #{name,jdbcType=VARCHAR},", "SURNAME = #{surname,jdbcType=VARCHAR}",
			"where ID = #{id,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(People record);
}