package it.rcpvision.emf.architecture.example.repository.mybatis.mapper;

import it.rcpvision.emf.architecture.example.repository.mybatis.model.Reservation;
import it.rcpvision.emf.architecture.example.repository.mybatis.model.ReservationExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @SelectProvider(type=ReservationSqlProvider.class, method="countByExample")
    long countByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @DeleteProvider(type=ReservationSqlProvider.class, method="deleteByExample")
    int deleteByExample(ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @Insert({
        "insert into USER1.RESERVATION (CAR, PEOPLE, ",
        "STATE)",
        "values (#{car,jdbcType=DECIMAL}, #{people,jdbcType=DECIMAL}, ",
        "#{state,jdbcType=DECIMAL})"
    })
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @InsertProvider(type=ReservationSqlProvider.class, method="insertSelective")
    int insertSelective(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @SelectProvider(type=ReservationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="CAR", property="car", jdbcType=JdbcType.DECIMAL),
        @Result(column="PEOPLE", property="people", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATE", property="state", jdbcType=JdbcType.DECIMAL)
    })
    List<Reservation> selectByExample(ReservationExample example);
    
    
    @Select({ "select", "CAR, PEOPLE, STATE", "FROM RESERVATION r, CAR c", 
    	"where r.CAR=c.ID and c.ID = #{id,jdbcType=DECIMAL}" })
    @Results({
        @Result(column="CAR", property="car", jdbcType=JdbcType.DECIMAL),
        @Result(column="PEOPLE", property="people", jdbcType=JdbcType.DECIMAL),
        @Result(column="STATE", property="state", jdbcType=JdbcType.DECIMAL)
    })
    List<Reservation> selectByVehicle(short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @UpdateProvider(type=ReservationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Reservation record, @Param("example") ReservationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.RESERVATION
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @UpdateProvider(type=ReservationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Reservation record, @Param("example") ReservationExample example);
}