<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="carsharing" nsURI="http://ecf2017/carsharing" nsPrefix="carsharing">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservation" upperBound="-1"
        eType="#//Reservation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CarType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reservationState" eType="#//ReservationState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reservation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" eType="#//Vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CarType">
    <eLiterals name="car"/>
    <eLiterals name="van" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReservationState">
    <eLiterals name="free" literal="free"/>
    <eLiterals name="reserved" value="1"/>
    <eLiterals name="started" value="2"/>
  </eClassifiers>
</ecore:EPackage>
