package it.rcpvision.emf.architecture.example.repository.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.ID
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.BRAND
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.MODEL
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.TYPE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.PLATE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private String plate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER1.CAR.SEATS
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    private Short seats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.ID
     *
     * @return the value of USER1.CAR.ID
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.ID
     *
     * @param id the value for USER1.CAR.ID
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.BRAND
     *
     * @return the value of USER1.CAR.BRAND
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.BRAND
     *
     * @param brand the value for USER1.CAR.BRAND
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.MODEL
     *
     * @return the value of USER1.CAR.MODEL
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.MODEL
     *
     * @param model the value for USER1.CAR.MODEL
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.TYPE
     *
     * @return the value of USER1.CAR.TYPE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.TYPE
     *
     * @param type the value for USER1.CAR.TYPE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.PLATE
     *
     * @return the value of USER1.CAR.PLATE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String getPlate() {
        return plate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.PLATE
     *
     * @param plate the value for USER1.CAR.PLATE
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setPlate(String plate) {
        this.plate = plate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER1.CAR.SEATS
     *
     * @return the value of USER1.CAR.SEATS
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public Short getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER1.CAR.SEATS
     *
     * @param seats the value for USER1.CAR.SEATS
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public void setSeats(Short seats) {
        this.seats = seats;
    }
}