package it.rcpvision.ecf2017.example.repository.mybatis.mapper;

import it.rcpvision.ecf2017.example.repository.mybatis.model.Car;
import it.rcpvision.ecf2017.example.repository.mybatis.model.CarExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @SelectProvider(type=CarSqlProvider.class, method="countByExample")
    long countByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @DeleteProvider(type=CarSqlProvider.class, method="deleteByExample")
    int deleteByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @Delete({
        "delete from USER1.CAR",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @Insert({
        "insert into USER1.CAR (ID, BRAND, ",
        "MODEL, TYPE, PLATE, ",
        "SEATS)",
        "values (#{id,jdbcType=DECIMAL}, #{brand,jdbcType=VARCHAR}, ",
        "#{model,jdbcType=VARCHAR}, #{type,jdbcType=DECIMAL}, #{plate,jdbcType=VARCHAR}, ",
        "#{seats,jdbcType=DECIMAL})"
    })
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @InsertProvider(type=CarSqlProvider.class, method="insertSelective")
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @SelectProvider(type=CarSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="BRAND", property="brand", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODEL", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE", property="plate", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEATS", property="seats", jdbcType=JdbcType.DECIMAL)
    })
    List<Car> selectByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @Select({
        "select",
        "ID, BRAND, MODEL, TYPE, PLATE, SEATS",
        "from USER1.CAR",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="BRAND", property="brand", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODEL", property="model", jdbcType=JdbcType.VARCHAR),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE", property="plate", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEATS", property="seats", jdbcType=JdbcType.DECIMAL)
    })
    Car selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @UpdateProvider(type=CarSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @UpdateProvider(type=CarSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @UpdateProvider(type=CarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    @Update({
        "update USER1.CAR",
        "set BRAND = #{brand,jdbcType=VARCHAR},",
          "MODEL = #{model,jdbcType=VARCHAR},",
          "TYPE = #{type,jdbcType=DECIMAL},",
          "PLATE = #{plate,jdbcType=VARCHAR},",
          "SEATS = #{seats,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Car record);
}