package it.rcpvision.ecf2017.example.repository.mybatis.mapper;

import it.rcpvision.ecf2017.example.repository.mybatis.model.Car;
import it.rcpvision.ecf2017.example.repository.mybatis.model.CarExample.Criteria;
import it.rcpvision.ecf2017.example.repository.mybatis.model.CarExample.Criterion;
import it.rcpvision.ecf2017.example.repository.mybatis.model.CarExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CarSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String countByExample(CarExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("USER1.CAR");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String deleteByExample(CarExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("USER1.CAR");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String insertSelective(Car record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("USER1.CAR");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=DECIMAL}");
        }
        
        if (record.getBrand() != null) {
            sql.VALUES("BRAND", "#{brand,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.VALUES("MODEL", "#{model,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("TYPE", "#{type,jdbcType=DECIMAL}");
        }
        
        if (record.getPlate() != null) {
            sql.VALUES("PLATE", "#{plate,jdbcType=VARCHAR}");
        }
        
        if (record.getSeats() != null) {
            sql.VALUES("SEATS", "#{seats,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String selectByExample(CarExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ID");
        } else {
            sql.SELECT("ID");
        }
        sql.SELECT("BRAND");
        sql.SELECT("MODEL");
        sql.SELECT("TYPE");
        sql.SELECT("PLATE");
        sql.SELECT("SEATS");
        sql.FROM("USER1.CAR");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Car record = (Car) parameter.get("record");
        CarExample example = (CarExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("USER1.CAR");
        
        if (record.getId() != null) {
            sql.SET("ID = #{record.id,jdbcType=DECIMAL}");
        }
        
        if (record.getBrand() != null) {
            sql.SET("BRAND = #{record.brand,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.SET("MODEL = #{record.model,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("TYPE = #{record.type,jdbcType=DECIMAL}");
        }
        
        if (record.getPlate() != null) {
            sql.SET("PLATE = #{record.plate,jdbcType=VARCHAR}");
        }
        
        if (record.getSeats() != null) {
            sql.SET("SEATS = #{record.seats,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("USER1.CAR");
        
        sql.SET("ID = #{record.id,jdbcType=DECIMAL}");
        sql.SET("BRAND = #{record.brand,jdbcType=VARCHAR}");
        sql.SET("MODEL = #{record.model,jdbcType=VARCHAR}");
        sql.SET("TYPE = #{record.type,jdbcType=DECIMAL}");
        sql.SET("PLATE = #{record.plate,jdbcType=VARCHAR}");
        sql.SET("SEATS = #{record.seats,jdbcType=DECIMAL}");
        
        CarExample example = (CarExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    public String updateByPrimaryKeySelective(Car record) {
        SQL sql = new SQL();
        sql.UPDATE("USER1.CAR");
        
        if (record.getBrand() != null) {
            sql.SET("BRAND = #{brand,jdbcType=VARCHAR}");
        }
        
        if (record.getModel() != null) {
            sql.SET("MODEL = #{model,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("TYPE = #{type,jdbcType=DECIMAL}");
        }
        
        if (record.getPlate() != null) {
            sql.SET("PLATE = #{plate,jdbcType=VARCHAR}");
        }
        
        if (record.getSeats() != null) {
            sql.SET("SEATS = #{seats,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=DECIMAL}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER1.CAR
     *
     * @mbg.generated Sat Jun 17 15:42:45 CEST 2017
     */
    protected void applyWhere(SQL sql, CarExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}