package it.rcpvision.ecf2017.example.repository.mybatis.mapper;

import it.rcpvision.ecf2017.example.repository.mybatis.model.People;
import it.rcpvision.ecf2017.example.repository.mybatis.model.PeopleExample.Criteria;
import it.rcpvision.ecf2017.example.repository.mybatis.model.PeopleExample.Criterion;
import it.rcpvision.ecf2017.example.repository.mybatis.model.PeopleExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PeopleSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String countByExample(PeopleExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("USER1.PEOPLE");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String deleteByExample(PeopleExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("USER1.PEOPLE");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String insertSelective(People record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("USER1.PEOPLE");
		if (record.getId() != null) {
			sql.VALUES("ID", "#{id,jdbcType=DECIMAL}");
		}
		if (record.getName() != null) {
			sql.VALUES("NAME", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getSurname() != null) {
			sql.VALUES("SURNAME", "#{surname,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String selectByExample(PeopleExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("ID");
		} else {
			sql.SELECT("ID");
		}
		sql.SELECT("NAME");
		sql.SELECT("SURNAME");
		sql.FROM("USER1.PEOPLE");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		People record = (People) parameter.get("record");
		PeopleExample example = (PeopleExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("USER1.PEOPLE");
		if (record.getId() != null) {
			sql.SET("ID = #{record.id,jdbcType=DECIMAL}");
		}
		if (record.getName() != null) {
			sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getSurname() != null) {
			sql.SET("SURNAME = #{record.surname,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("USER1.PEOPLE");
		sql.SET("ID = #{record.id,jdbcType=DECIMAL}");
		sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
		sql.SET("SURNAME = #{record.surname,jdbcType=VARCHAR}");
		PeopleExample example = (PeopleExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	public String updateByPrimaryKeySelective(People record) {
		SQL sql = new SQL();
		sql.UPDATE("USER1.PEOPLE");
		if (record.getName() != null) {
			sql.SET("NAME = #{name,jdbcType=VARCHAR}");
		}
		if (record.getSurname() != null) {
			sql.SET("SURNAME = #{surname,jdbcType=VARCHAR}");
		}
		sql.WHERE("ID = #{id,jdbcType=DECIMAL}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER1.PEOPLE
	 * @mbg.generated  Sat Jun 17 15:42:45 CEST 2017
	 */
	protected void applyWhere(SQL sql, PeopleExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}